[lib]
crate-type = ["cdylib"]

[package]
name = "zipper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Used source: https://github.com/rust-lang/flate2-rs
zip = "0.5"
flate2 = "1.0"
